// ESLint Flat Config for claude-session-topics
// Compatible with ESLint v9+

export default [
  {
    files: ['bin/**/*.js', 'scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        Promise: 'readonly',
      },
    },
    rules: {
      // Possible Errors
      'no-cond-assign': 'error',
      'no-constant-condition': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'warn',
      'no-ex-assign': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-irregular-whitespace': 'error',
      'no-obj-calls': 'error',
      'no-sparse-arrays': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // Best Practices
      'no-alert': 'warn',
      'no-caller': 'error',
      'no-else-return': 'warn',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'warn',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'warn',
      'no-loop-func': 'error',
      'no-multi-spaces': 'warn',
      'no-multi-str': 'warn',
      'no-new': 'warn',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': 'warn',
      'no-useless-call': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-escape': 'warn',
      'no-void': 'warn',
      'no-warning-comments': ['warn', { terms: ['todo', 'fixme'], location: 'start' }],
      'no-with': 'error',
      'prefer-const': 'warn',

      // Variables
      'no-delete-var': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'error',
      'no-undef-init': 'warn',
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],

      // Stylistic Issues
      'array-bracket-spacing': ['warn', 'never'],
      'block-spacing': ['warn', 'always'],
      'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
      'camelcase': ['warn', { properties: 'never' }],
      'comma-dangle': ['warn', 'always-multiline'],
      'comma-spacing': ['warn', { before: false, after: true }],
      'comma-style': ['warn', 'last'],
      'computed-property-spacing': ['warn', 'never'],
      'eol-last': ['warn', 'always'],
      'func-call-spacing': ['warn', 'never'],
      'indent': ['warn', 4, { SwitchCase: 1 }],
      'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
      'keyword-spacing': ['warn', { before: true, after: true }],
      'linebreak-style': ['warn', 'unix'],
      'new-cap': ['warn', { newIsCap: true, capIsNew: false }],
      'new-parens': 'warn',
      'no-array-constructor': 'error',
      'no-bitwise': 'warn',
      'no-lonely-if': 'warn',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multiple-empty-lines': ['warn', { max: 2 }],
      'no-nested-ternary': 'warn',
      'no-new-object': 'error',
      'no-trailing-spaces': 'warn',
      'no-unneeded-ternary': 'warn',
      'no-whitespace-before-property': 'warn',
      'object-curly-spacing': ['warn', 'always'],
      'operator-linebreak': ['warn', 'after'],
      'quote-props': ['warn', 'as-needed'],
      'quotes': ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
      'semi': ['warn', 'always'],
      'semi-spacing': ['warn', { before: false, after: true }],
      'space-before-blocks': ['warn', 'always'],
      'space-before-function-paren': ['warn', 'never'],
      'space-in-parens': ['warn', 'never'],
      'space-infix-ops': 'warn',
      'space-unary-ops': ['warn', { words: true, nonwords: false }],
      'template-curly-spacing': ['warn', 'never'],
    },
  },
];
