#!/usr/bin/env python3
"""Tests for extract_topic.py"""

import os
import sys
import unittest

# Import the module with corrected path for tests/python/ location
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'scripts'))
from extract_topic import extract_topic


TEST_CASES = [
    # ── English messages ──
    {
        "num": 1,
        "input": "Add a new search filter to the dashboard",
        "check_contains": ["Search"],
    },
    {
        "num": 4,
        "input": "Fix the authentication error in NeonDB session handling",
        "check_contains": ["NeonDB", "Authentication", "Session"],
    },
    {
        "num": 5,
        "input": "Help me debug the React Query cache invalidation",
        "expected": "React Query Cache Invalidation",
    },
    {
        "num": 7,
        "input": "Fix bug",
        "expected": "Bug Fix",
    },
    {
        "num": 8,
        "input": "I need to refactor the database migration scripts",
        "expected": "Database Migration Scripts",
    },
    # ── Spanish messages → English-only policy: return empty ──
    {
        "num": 2,
        "input": "Hola, necesito ayuda con el componente de autenticación de NextAuth",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 3,
        "input": "Corrige el error de autenticación en NeonDB",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 6,
        "input": "Revisa los tests de la API de pagos",
        "expected": "Tests API",
        "description": "Mixed text with tech terms - extracts English keywords",
    },
    {
        "num": 9,
        "input": "Implementa rate limiting en el endpoint de login",
        "expected": "Rate Limiting Endpoint Login",
        "description": "Mixed text with tech terms - extracts English keywords",
    },
    {
        "num": 10,
        "input": "Actualiza las dependencias de Docker Compose",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 20,
        "input": "Necesitan reajustar los esqueletos de la pantalla de perfil",
        "expected": "",
        "description": "all-Spanish → empty (LLM skill handles it)",
    },
    {
        "num": 21,
        "input": "Configura el endpoint de autenticación con NextAuth y NeonDB",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 22,
        "input": "Investiga por qué el hook de session topic genera basura",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 23,
        "input": "Implementa rate limiting en el endpoint de login",
        "expected": "Rate Limiting Endpoint Login",
        "description": "Mixed text with tech terms - extracts English keywords",
    },
    # ── Markdown image stripping ──
    {
        "num": 11,
        "input": "![Image 1 Screen Profile Desktop](file:///Users/mac/Desktop/screenshot.png) Fix the topic extraction",
        "check_contains": ["Topic", "Extraction"],
        "check_excludes": ["Image", "Screen", "Profile", "Desktop"],
    },
    {
        "num": 12,
        "input": "Check this ![error screenshot](https://example.com/img.png) in the API endpoint",
        "check_contains": ["API", "Endpoint"],
        "check_excludes": ["screenshot"],
    },
    {
        "num": 13,
        "input": "![](file:///tmp/image.png) debug the session hook",
        "check_contains": ["Session", "Hook"],
    },
    # ── Markdown links ──
    {
        "num": 14,
        "input": "Read [this documentation](https://docs.example.com/auth) about OAuth setup",
        "check_contains": ["Documentation", "OAuth"],
    },
    # ── URLs ──
    {
        "num": 15,
        "input": "Open file:///Users/mac/projects/app/config.yaml and review the settings",
        "check_contains": ["Settings"],
        "check_excludes": ["file", "Users", "mac", "yaml"],
    },
    {
        "num": 16,
        "input": "![step 1](file:///a.png) ![step 2](file:///b.png) Configure the Nginx proxy",
        "check_contains": ["Nginx", "Proxy"],
        "check_excludes": ["step"],
    },
    # ── Claude Code metadata blocks ──
    {
        "num": 17,
        "input": "Fix the login <system-reminder>task tools reminder blah</system-reminder> page redirect",
        "check_contains": ["Login", "Page", "Redirect"],
        "check_excludes": ["task", "tools", "reminder"],
    },
    {
        "num": 18,
        "input": (
            '<local-command-caveat>Caveat: The messages below were generated by the user while '
            'running local commands. DO NOT respond.</local-command-caveat>\n'
            '<command-name>/clear</command-name>\n'
            '<command-message>clear</command-message>\n'
            '<command-args></command-args>\n'
            '<local-command-stdout></local-command-stdout>\n'
            'Fix the session topic extraction'
        ),
        "check_contains": ["Session", "Topic", "Extraction"],
        "check_excludes": ["Messages", "Generated", "Running", "Caveat", "clear"],
    },
    {
        "num": 19,
        "input": (
            '<local-command-caveat>Caveat: messages generated by user running local commands'
            '</local-command-caveat>\nDebug the Nginx proxy config'
        ),
        "check_contains": ["Nginx", "Proxy", "Config"],
        "check_excludes": ["Messages", "Generated", "Running"],
    },
    # ── Real bug: /develop command with user text inside <command-args> ──
    {
        "num": 24,
        "input": (
            '<command-message>develop</command-message>\n'
            '<command-name>/develop</command-name>\n'
            '<command-args>--auto Adapta al diseño de desktop todo el flujo de inicio de sesión'
            '</command-args>'
        ),
        "expected": "",
        "description": "all text inside tags + Spanish → empty",
    },
    {
        "num": 25,
        "input": (
            '<command-message>develop</command-message>\n'
            '<command-name>/develop</command-name>\n'
            '<command-args>--auto Fix the NextAuth login flow for desktop</command-args>'
        ),
        "expected": "",
        "description": "all text inside tags → stripped (even if English)",
    },
    # ── Command tokens ──
    {
        "num": 26,
        "input": "--auto --verbose Fix the NextAuth login flow",
        "check_contains": ["NextAuth", "Login", "Flow"],
        "check_excludes": ["auto", "verbose"],
        "description": "command flags stripped from loose text",
    },
    # ── ñ detection ──
    {
        "num": 27,
        "input": "Modifica el diseño de la pestaña de búsqueda",
        "expected": "",
        "description": "diseño contains ñ → all Spanish → empty",
    },
    # ── Semantic coherence tests ──
    {
        "num": 28,
        "input": "Image rendering on entry screen for club members",
        "check_contains": ["Image", "Rendering"],
        "description": "YAKE selects statistically relevant terms - verify Image and Rendering present",
    },
    {
        "num": 29,
        "input": "Configure entra ID for club screen image",
        "check_contains": ["Entra", "ID"],
        "description": "YAKE prioritizes technical terms - verify Entra and ID present",
    },
    {
        "num": 30,
        "input": "Button click handler form validation error message",
        "check_contains": ["Button", "Form"],
        "description": "YAKE selects UI-related terms - accept any coherent 2-4 word combination",
    },
    {
        "num": 31,
        "input": "Fix database connection pool timeout issue in production",
        "check_contains": ["Database", "Connection"],
        "description": "YAKE preserves core technical terms - verify Database and Connection present",
    },
    {
        "num": 32,
        "input": "User profile avatar image upload crop resize feature",
        "check_contains": ["User", "Profile"],
        "description": "YAKE identifies entity terms - verify User and Profile present",
    },
    {
        "num": 33,
        "input": "API response data format JSON parsing error handling",
        "check_contains": ["API", "Response"],
        "description": "YAKE captures API context - verify API and Response present",
    },
    {
        "num": 34,
        "input": "Server endpoint request method GET POST parameters",
        "check_contains": ["Server", "Endpoint"],
        "description": "YAKE identifies infrastructure terms - verify Server and Endpoint present",
    },
    # ── Bug fix: Spanish detection - empty for Spanish-heavy texts ──
    {
        "num": 35,
        "input": "![Image](url) Emigró el modal a la versión desktop",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 36,
        "input": "El componente migra a la nueva arquitectura",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 37,
        "input": "Montan modales alrededor background",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    {
        "num": 38,
        "input": "Montar el modal en el background",
        "expected": "Modal Background",
        "description": "Mixed text with tech terms - extracts English keywords",
    },
    {
        "num": 39,
        "input": "Ventanas y modales en el desktop",
        "expected": "",
        "description": "Spanish-heavy text → empty (LLM skill handles it)",
    },
    # ── Bug fix: Spanish dimension words ──
    {
        "num": 40,
        "input": "Screen profile ancho 900px",
        "check_contains": ["Screen", "Profile", "900px"],
        "check_excludes": ["Ancho"],
        "description": "Bug fix: Spanish dimension word 'ancho' filtered",
    },
    {
        "num": 41,
        "input": "Fix profile width 900px",
        "check_contains": ["Profile", "Width", "900px"],
        "description": "English dimension words work correctly",
    },
]


class TestExtractTopic(unittest.TestCase):
    """Test cases for extract_topic function"""
    
    @classmethod
    def setUpClass(cls):
        """Print header before running tests"""
        print("=" * 70)
        print("  extract_topic() — Test Results")
        print("=" * 70)
        print()
    
    def _run_test_case(self, tc):
        """Run a single test case and return (passed, message)"""
        result = extract_topic(tc["input"])
        ok = True
        detail = f'Got: "{result}"'
        
        if "expected" in tc:
            if result != tc["expected"]:
                ok = False
                detail = f'Expected: "{tc["expected"]}", Got: "{result}"'
        
        if ok and "check_contains" in tc:
            missing = [w for w in tc["check_contains"] if w.lower() not in result.lower()]
            if missing:
                ok = False
                detail = f'Missing: {missing}. Got: "{result}"'
        
        if ok and "check_excludes" in tc:
            found = [w for w in tc["check_excludes"] if w.lower() in result.lower()]
            if found:
                ok = False
                detail += f' — UNWANTED: {found}'
        
        return ok, detail
    
    def test_case_01_search_filter(self):
        """Test 1: Add a new search filter to the dashboard"""
        tc = TEST_CASES[0]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_02_spanish_nextauth(self):
        """Test 2: Spanish-heavy text → empty"""
        tc = TEST_CASES[1]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_03_spanish_neondb(self):
        """Test 3: Spanish-heavy text → empty"""
        tc = TEST_CASES[2]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_04_auth_error_neondb(self):
        """Test 4: Fix the authentication error in NeonDB session handling"""
        tc = TEST_CASES[3]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_05_react_query_cache(self):
        """Test 5: Help me debug the React Query cache invalidation"""
        tc = TEST_CASES[4]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_06_tests_api_pagos(self):
        """Test 6: Mixed text with tech terms - extracts English keywords"""
        tc = TEST_CASES[5]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_07_fix_bug(self):
        """Test 7: Fix bug"""
        tc = TEST_CASES[6]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_08_database_migration(self):
        """Test 8: I need to refactor the database migration scripts"""
        tc = TEST_CASES[7]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_09_rate_limiting_login(self):
        """Test 9: Mixed text with tech terms - extracts English keywords"""
        tc = TEST_CASES[8]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_10_docker_compose(self):
        """Test 10: Spanish-heavy text → empty"""
        tc = TEST_CASES[9]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_11_markdown_image_stripping(self):
        """Test 11: Markdown image stripping"""
        tc = TEST_CASES[10]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_12_api_endpoint_screenshot(self):
        """Test 12: Check this screenshot in the API endpoint"""
        tc = TEST_CASES[11]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_13_session_hook(self):
        """Test 13: debug the session hook"""
        tc = TEST_CASES[12]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_14_oauth_documentation(self):
        """Test 14: Read documentation about OAuth setup"""
        tc = TEST_CASES[13]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_15_file_url(self):
        """Test 15: Open config.yaml and review settings"""
        tc = TEST_CASES[14]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_16_nginx_proxy(self):
        """Test 16: Configure the Nginx proxy"""
        tc = TEST_CASES[15]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_17_login_page_redirect(self):
        """Test 17: Fix the login page redirect"""
        tc = TEST_CASES[16]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_18_session_topic_extraction(self):
        """Test 18: Fix the session topic extraction"""
        tc = TEST_CASES[17]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_19_nginx_proxy_config(self):
        """Test 19: Debug the Nginx proxy config"""
        tc = TEST_CASES[18]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_20_spanish_skeletons(self):
        """Test 20: all-Spanish → empty"""
        tc = TEST_CASES[19]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_21_spanish_nextauth_config(self):
        """Test 21: Spanish-heavy text → empty"""
        tc = TEST_CASES[20]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_22_spanish_session_hook(self):
        """Test 22: Spanish-heavy text → empty"""
        tc = TEST_CASES[21]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_23_rate_limiting_login_mixed(self):
        """Test 23: Mixed text with tech terms - extracts English keywords"""
        tc = TEST_CASES[22]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_24_develop_command_spanish(self):
        """Test 24: all text inside tags + Spanish → empty"""
        tc = TEST_CASES[23]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_25_develop_command_english(self):
        """Test 25: all text inside tags → stripped (even if English)"""
        tc = TEST_CASES[24]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_26_command_flags_stripped(self):
        """Test 26: command flags stripped from loose text"""
        tc = TEST_CASES[25]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_27_spanish_n_detection(self):
        """Test 27: diseño contains ñ → all Spanish → empty"""
        tc = TEST_CASES[26]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_28_image_rendering(self):
        """Test 28: YAKE selects statistically relevant terms"""
        tc = TEST_CASES[27]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_29_entra_id(self):
        """Test 29: YAKE prioritizes technical terms"""
        tc = TEST_CASES[28]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_30_button_form(self):
        """Test 30: YAKE selects UI-related terms"""
        tc = TEST_CASES[29]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_31_database_connection(self):
        """Test 31: YAKE preserves core technical terms"""
        tc = TEST_CASES[30]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_32_user_profile(self):
        """Test 32: YAKE identifies entity terms"""
        tc = TEST_CASES[31]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_33_api_response(self):
        """Test 33: YAKE captures API context"""
        tc = TEST_CASES[32]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_34_server_endpoint(self):
        """Test 34: YAKE identifies infrastructure terms"""
        tc = TEST_CASES[33]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_35_spanish_modal_version(self):
        """Test 35: Spanish-heavy text → empty"""
        tc = TEST_CASES[34]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_36_spanish_component_architecture(self):
        """Test 36: Spanish-heavy text → empty"""
        tc = TEST_CASES[35]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_37_spanish_modales_background(self):
        """Test 37: Spanish-heavy text → empty"""
        tc = TEST_CASES[36]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_38_mixed_modal_background(self):
        """Test 38: Mixed text with tech terms - extracts English keywords"""
        tc = TEST_CASES[37]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_39_spanish_windows_modals(self):
        """Test 39: Spanish-heavy text → empty"""
        tc = TEST_CASES[38]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_40_spanish_dimension_word(self):
        """Test 40: Bug fix: Spanish dimension word 'ancho' filtered"""
        tc = TEST_CASES[39]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)
    
    def test_case_41_english_dimension_word(self):
        """Test 41: English dimension words work correctly"""
        tc = TEST_CASES[40]
        ok, detail = self._run_test_case(tc)
        self.assertTrue(ok, detail)


def run_tests():
    """Run tests and return True if all passed"""
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestExtractTopic)
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    return result.wasSuccessful()


def run_tests_with_junit(output_dir="test-reports"):
    """Run tests with JUnit XML output for CI"""
    try:
        import xmlrunner
        os.makedirs(output_dir, exist_ok=True)
        loader = unittest.TestLoader()
        suite = loader.loadTestsFromTestCase(TestExtractTopic)
        
        with open(os.path.join(output_dir, "TEST-test_extract_topic.xml"), 'wb') as output:
            runner = xmlrunner.XMLTestRunner(output=output, verbosity=2)
            result = runner.run(suite)
        
        return result.wasSuccessful()
    except ImportError:
        print("xmlrunner not installed. Run: pip3 install unittest-xml-reporting")
        return run_tests()


if __name__ == "__main__":
    # Check for JUnit XML output flag
    if "--junitxml" in sys.argv or "--ci" in sys.argv:
        success = run_tests_with_junit()
    else:
        success = run_tests()
    
    sys.exit(0 if success else 1)