#!/usr/bin/env python3
"""Tests for extract_topic.py"""

import os
import sys

# Import the module directly — no more copy-paste
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_topic import extract_topic


TEST_CASES = [
    # ── English messages ──
    {
        "num": 1,
        "input": "Add a new search filter to the dashboard",
        "check_contains": ["Search"],
    },
    {
        "num": 4,
        "input": "Fix the authentication error in NeonDB session handling",
        "check_contains": ["NeonDB", "Authentication", "Session"],
    },
    {
        "num": 5,
        "input": "Help me debug the React Query cache invalidation",
        "expected": "React Query Cache Invalidation",
    },
    {
        "num": 7,
        "input": "Fix bug",
        "expected": "Bug Fix",
    },
    {
        "num": 8,
        "input": "I need to refactor the database migration scripts",
        "expected": "Database Migration Scripts",
    },
    # ── Spanish messages → extract keywords ──
    {
        "num": 2,
        "input": "Hola, necesito ayuda con el componente de autenticación de NextAuth",
        "expected": "Componente Autenticación NextAuth",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 3,
        "input": "Corrige el error de autenticación en NeonDB",
        "expected": "Corrige Error Autenticación NeonDB",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 6,
        "input": "Revisa los tests de la API de pagos",
        "expected": "Revisa Tests API Pagos",
        "description": "Mixed text extracts all keywords",
    },
    {
        "num": 9,
        "input": "Implementa rate limiting en el endpoint de login",
        "expected": "Implementa Rate Limiting Endpoint",
        "description": "Mixed text extracts all keywords",
    },
    {
        "num": 10,
        "input": "Actualiza las dependencias de Docker Compose",
        "expected": "Actualiza Dependencias Docker Compose",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 20,
        "input": "Necesitan reajustar los esqueletos de la pantalla de perfil",
        "expected": "Necesitan Reajustar Esqueletos Pantalla",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 21,
        "input": "Configura el endpoint de autenticación con NextAuth y NeonDB",
        "expected": "Configura Endpoint Autenticación NextAuth",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 22,
        "input": "Investiga por qué el hook de session topic genera basura",
        "expected": "Investiga Hook Session Topic",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 23,
        "input": "Implementa rate limiting en el endpoint de login",
        "expected": "Implementa Rate Limiting Endpoint",
        "description": "Mixed text extracts all keywords",
    },
    # ── Markdown image stripping ──
    {
        "num": 11,
        "input": "![Image 1 Screen Profile Desktop](file:///Users/mac/Desktop/screenshot.png) Fix the topic extraction",
        "check_contains": ["Topic", "Extraction"],
        "check_excludes": ["Image", "Screen", "Profile", "Desktop"],
    },
    {
        "num": 12,
        "input": "Check this ![error screenshot](https://example.com/img.png) in the API endpoint",
        "check_contains": ["API", "Endpoint"],
        "check_excludes": ["screenshot"],
    },
    {
        "num": 13,
        "input": "![](file:///tmp/image.png) debug the session hook",
        "check_contains": ["Session", "Hook"],
    },
    # ── Markdown links ──
    {
        "num": 14,
        "input": "Read [this documentation](https://docs.example.com/auth) about OAuth setup",
        "check_contains": ["Documentation", "OAuth"],
    },
    # ── URLs ──
    {
        "num": 15,
        "input": "Open file:///Users/mac/projects/app/config.yaml and review the settings",
        "check_contains": ["Settings"],
        "check_excludes": ["file", "Users", "mac", "yaml"],
    },
    {
        "num": 16,
        "input": "![step 1](file:///a.png) ![step 2](file:///b.png) Configure the Nginx proxy",
        "check_contains": ["Nginx", "Proxy"],
        "check_excludes": ["step"],
    },
    # ── Claude Code metadata blocks ──
    {
        "num": 17,
        "input": "Fix the login <system-reminder>task tools reminder blah</system-reminder> page redirect",
        "check_contains": ["Login", "Page", "Redirect"],
        "check_excludes": ["task", "tools", "reminder"],
    },
    {
        "num": 18,
        "input": (
            '<local-command-caveat>Caveat: The messages below were generated by the user while '
            'running local commands. DO NOT respond.</local-command-caveat>\n'
            '<command-name>/clear</command-name>\n'
            '<command-message>clear</command-message>\n'
            '<command-args></command-args>\n'
            '<local-command-stdout></local-command-stdout>\n'
            'Fix the session topic extraction'
        ),
        "check_contains": ["Session", "Topic", "Extraction"],
        "check_excludes": ["Messages", "Generated", "Running", "Caveat", "clear"],
    },
    {
        "num": 19,
        "input": (
            '<local-command-caveat>Caveat: messages generated by user running local commands'
            '</local-command-caveat>\nDebug the Nginx proxy config'
        ),
        "check_contains": ["Nginx", "Proxy", "Config"],
        "check_excludes": ["Messages", "Generated", "Running"],
    },
    # ── Real bug: /develop command with user text inside <command-args> ──
    {
        "num": 24,
        "input": (
            '<command-message>develop</command-message>\n'
            '<command-name>/develop</command-name>\n'
            '<command-args>--auto Adapta al diseño de desktop todo el flujo de inicio de sesión'
            '</command-args>'
        ),
        "expected": "",
        "description": "all text inside tags + Spanish → empty",
    },
    {
        "num": 25,
        "input": (
            '<command-message>develop</command-message>\n'
            '<command-name>/develop</command-name>\n'
            '<command-args>--auto Fix the NextAuth login flow for desktop</command-args>'
        ),
        "expected": "",
        "description": "all text inside tags → stripped (even if English)",
    },
    # ── Command tokens ──
    {
        "num": 26,
        "input": "--auto --verbose Fix the NextAuth login flow",
        "check_contains": ["NextAuth", "Login", "Flow"],
        "check_excludes": ["auto", "verbose"],
        "description": "command flags stripped from loose text",
    },
    # ── ñ detection ──
    {
        "num": 27,
        "input": "Modifica el diseño de la pestaña de búsqueda",
        "expected": "Modifica Diseño Pestaña Búsqueda",
        "description": "Spanish text with ñ extracts keywords",
    },
    # ── Semantic coherence tests ──
    {
        "num": 28,
        "input": "Image rendering on entry screen for club members",
        "check_contains": ["Rendering"],
        "description": "YAKE selects statistically relevant terms - verify Rendering present",
    },
    {
        "num": 29,
        "input": "Configure entra ID for club screen image",
        "check_contains": ["Entra", "ID"],
        "description": "YAKE prioritizes technical terms - verify Entra and ID present",
    },
    {
        "num": 30,
        "input": "Button click handler form validation error message",
        "check_contains": ["Button", "Form"],
        "description": "YAKE selects UI-related terms - accept any coherent 2-4 word combination",
    },
    {
        "num": 31,
        "input": "Fix database connection pool timeout issue in production",
        "check_contains": ["Database", "Connection"],
        "description": "YAKE preserves core technical terms - verify Database and Connection present",
    },
    {
        "num": 32,
        "input": "User profile avatar image upload crop resize feature",
        "check_contains": ["User", "Profile"],
        "description": "YAKE identifies entity terms - verify User and Profile present",
    },
    {
        "num": 33,
        "input": "API response data format JSON parsing error handling",
        "check_contains": ["API", "Response"],
        "description": "YAKE captures API context - verify API and Response present",
    },
    {
        "num": 34,
        "input": "Server endpoint request method GET POST parameters",
        "check_contains": ["Server", "Endpoint"],
        "description": "YAKE identifies infrastructure terms - verify Server and Endpoint present",
    },
    # ── Bug fix: Spanish detection - extract keywords from Spanish texts ──
    {
        "num": 35,
        "input": "![Image](url) Emigró el modal a la versión desktop",
        "expected": "Emigró Modal Versión Desktop",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 36,
        "input": "El componente migra a la nueva arquitectura",
        "expected": "Componente Migra Nueva Arquitectura",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 37,
        "input": "Montan modales alrededor background",
        "expected": "Montan Modales Alrededor Background",
        "description": "Spanish text extracts keywords in Spanish",
    },
    {
        "num": 38,
        "input": "Montar el modal en el background",
        "expected": "Montar Modal Background",
        "description": "Mixed text extracts all keywords",
    },
    {
        "num": 39,
        "input": "Ventanas y modales en el desktop",
        "expected": "Ventanas Modales Desktop",
        "description": "Spanish text extracts keywords in Spanish",
    },
    # ── Bug fix: Spanish dimension words ──
    {
        "num": 40,
        "input": "Screen profile ancho 900px",
        "expected": "Screen Profile Ancho 900px",
        "description": "Dimension words included in topic",
    },
    {
        "num": 41,
        "input": "Fix profile width 900px",
        "check_contains": ["Profile", "Width", "900px"],
        "description": "English dimension words work correctly",
    },
]


def run_tests():
    passed = 0
    failed = 0

    print("=" * 70)
    print("  extract_topic() — Test Results")
    print("=" * 70)
    print()

    for tc in TEST_CASES:
        result = extract_topic(tc["input"])
        ok = True
        detail = f'Got: "{result}"'

        if "expected" in tc:
            if result != tc["expected"]:
                ok = False
                detail = f'Expected: "{tc["expected"]}", Got: "{result}"'

        if ok and "check_contains" in tc:
            missing = [w for w in tc["check_contains"] if w.lower() not in result.lower()]
            if missing:
                ok = False
                detail = f'Missing: {missing}. Got: "{result}"'

        if ok and "check_excludes" in tc:
            found = [w for w in tc["check_excludes"] if w.lower() in result.lower()]
            if found:
                ok = False
                detail += f' — UNWANTED: {found}'

        icon = "✓" if ok else "✗"
        status = "PASS" if ok else "FAIL"
        desc = tc.get("description", "")
        if ok:
            passed += 1
        else:
            failed += 1

        print(f"  {icon} Test {tc['num']}: [{status}] {desc}")
        print(f"    {detail}")
        print()

    total = passed + failed
    print("=" * 70)
    print(f"  TOTAL: {total}  |  PASSED: {passed}  |  FAILED: {failed}")
    print("=" * 70)
    return failed == 0


if __name__ == "__main__":
    sys.exit(0 if run_tests() else 1)
